Add support for sharedGalleryImageID in azure image reference
gardener/machine-controller-manager-provider-azure pull request #73
Opened 2022-09-02 10:47 UTC by rishabh-11

**What this PR does / why we need it**:

- Add support for machines based on shared gallery images

**Which issue(s) this PR fixes**:
Fixes #71 

**Special notes for your reviewer**:
SharedGalleryImageID eg:- `/SharedGalleries/<sharedGalleryName>/Images/<sharedGalleryImageName>/Versions/<sharedGalleryImageVersionName>`

**Release note**:

```improvement user
Machine-Controller-Manager Provider-Azure now supports managing virtual machines based on shared image gallery images. 
```

/invite @himanshu-kun

2022-09-02 19:09 UTC, himanshu-kun requested changes

2022-09-02 19:09 UTC, himanshu-kun commented on pkg/azure/apis/validation/validation.go
> +			return append(allErrs, field.Required(fldPath.Child("urn"), "cannot specify a urn and community gallery image id, shared gallery image id or image id in parallel"))
```suggestion
			return append(allErrs, field.Required(fldPath.Child("urn"), "cannot specify community gallery image id, shared gallery image id or image id when urn is specified"))
```

2022-09-02 19:09 UTC, himanshu-kun commented on pkg/azure/apis/validation/validation.go
> +			return append(allErrs, field.Required(fldPath.Child("communityGalleryImageID"), "cannot specify a community image gallery id and shared image gallery id or image id in parallel"))
```suggestion
			return append(allErrs, field.Required(fldPath.Child("communityGalleryImageID"), "cannot specify shared gallery image id or image id when community gallery image id is specified"))
```

2022-09-05 10:31 UTC, rishabh-11 commented on pkg/azure/apis/validation/validation.go
> +			return append(allErrs, field.Required(fldPath.Child("urn"), "cannot specify a urn and community gallery image id, shared gallery image id or image id in parallel"))
done

2022-09-05 10:31 UTC, rishabh-11 commented on pkg/azure/apis/validation/validation.go
> +			return append(allErrs, field.Required(fldPath.Child("communityGalleryImageID"), "cannot specify a community image gallery id and shared image gallery id or image id in parallel"))
done

2022-09-06 05:59 UTC, himanshu-kun approved these changes
/lgtm

2022-09-06 05:59 UTC, merged

2022-09-09 09:15 UTC, himanshu-kun commented
/woof

2022-09-09 09:16 UTC, himanshu-kun commented
/joke

2022-09-09 09:17 UTC, himanshu-kun commented
/test ?